version: '3'

volumes:
    logs:
        driver: local

services:
    slim-app:
        build: .docker/php
        container_name: slim-app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        networks:
            - slim-network
        tty: true

    slim-nginx:
        build: .docker/nginx
        container_name: slim-nginx
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - slim-network

    slim-db:
        build: .docker/mysql
        container_name: slim-db
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=slim
            - MYSQL_ROOT_PASSWORD=slim_password
        networks:
            - slim-network

    slim-phpmyadmin:
        image: phpmyadmin
        container_name: slim-phpmyadmin
        ports:
            - "8081:80"
        links:
            - slim-db
        depends_on:
            - slim-db
        environment:
            PMA_HOST: slim-db
        networks:
            - slim-network

networks:
    slim-network:
        driver: bridge
